name: jlf_mobile
description: A new Flutter project.

version: 0.1.6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^1.3.0
  validators: ^1.0.0+1
  http: ^0.12.0
  shared_preferences: ^0.5.1
  flutter_masked_text: ^0.8.0
  multi_image_picker: ^4.3.4
  image_picker: ^0.6.1
  image_cropper: ^1.0.2
  permission_handler: '^3.2.0'
  mailer: ^2.2.1
  video_player: ^0.10.2
  flutter_facebook_login:
    git: 
      url: https://github.com/yudaprama/flutter_facebook_login
      ref: android-x
  flutter_video_compress: ^0.3.7+8
  firebase_storage: ^3.0.4

  # Firebase Notifications
  firebase_core: ^0.4.0+6
  # firebase_auth:
  cloud_firestore: ^0.12.5+2
  firebase_messaging: ^5.0.4
  firebase_analytics: ^4.0.2
  
  url_launcher: ^5.0.3

  flutter_webview_plugin: ^0.3.5
  share: ^0.6.2

  photo_view: ^0.4.2
  uni_links: ^0.2.0

  flutter_local_notifications: ^0.8.1

  youtube_player_flutter: ^4.0.0+1

  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git

  carousel_pro: ^1.0.0
  cached_network_image: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/jlf-back.png
    - assets/images/Facebook.png
    - assets/images/loading.gif
    - assets/images/error.jpeg
    - assets/images/account.png
    - assets/images/logo.png
    - assets/images/image_not_found.png
    - assets/images/comment.png
    - assets/images/intro/1.png
    - assets/images/intro/2.png
    - assets/images/intro/3.png
    - assets/images/intro/4.png
    - assets/images/intro/5.png
    - assets/images/whatsapp.png
    - assets/images/about-jlf.jpeg
    - assets/images/faq.jpeg
    - assets/images/rekber-pembeli.jpeg
    - assets/images/rekber-penjual.jpeg
    - assets/images/bid.jpeg
    - assets/images/donation.jpeg
    - assets/images/new_update.png
    - assets/images/peoplecount.png
    - assets/images/animalcount.png
    - assets/images/calendar.png
    - assets/images/daftar_binatang_dilarang.jpg
    - assets/images/jlf-blue.png
    - assets/images/pets_login.jpg                
    - assets/images/donation_banner.png

  fonts:
  - family: RobotoMono
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
 