name: jlf_mobile
description: Jual Lelang Fauna.

version: 0.1.9

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^1.3.1
  validators: ^1.0.0+1
  http: ^0.12.0
  shared_preferences: ^0.5.1
  flutter_masked_text: ^0.8.0
  multi_image_picker: ^4.5.8
  image_picker: ^0.6.1+8
  image_cropper: 1.0.2
  permission_handler: ^3.3.0
  mailer: ^2.5.1
  video_player: ^0.10.2+5
  pinput: ^0.1.10
  toast: ^0.1.5
 
  flutter_facebook_login: ^3.0.0
  flutter_video_compress: ^0.3.7+8

  #pdf viewer for not statefull widget
  flutter_plugin_pdf_viewer: ^1.0.7
  flutter_datetime_picker: ^1.2.8

  # flutter_swiper: ^1.1.6
  
  # Firebase
  firebase_storage: ^3.0.6
  firebase_core: ^0.4.0+9
  # firebase_auth:
  cloud_firestore: ^0.12.5+2
  firebase_messaging: 5.1.5
  firebase_analytics: ^5.0.2

  flutter_html: ^0.11.0

  datetime_picker_formfield: ^0.4.3
  
  url_launcher: ^5.0.3

  flutter_webview_plugin: ^0.3.8
  share: ^0.6.2
  

  photo_view: ^0.4.2
  uni_links: ^0.2.0

  flutter_local_notifications: ^0.8.1

  youtube_player_flutter: ^4.1.0

  flutter_native_image: ^0.0.4
    # git: https://github.com/btastic/flutter_native_image.git

  carousel_pro: ^1.0.0
  cached_network_image: ^1.1.2+1
  image_downloader: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # flutter change launcher icon
  flutter_launcher_icons: 0.7.3

flutter_icons:
  # android: "launcher_icon" 
  ios: true
  image_path: "assets/appicon/appicon_super.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/jlf-back.png
    - assets/images/Facebook.png
    - assets/images/loading.gif
    - assets/images/error.jpeg
    - assets/images/account.png
    - assets/images/logo.png
    - assets/images/image_not_found.png
    - assets/images/comment.png
    - assets/images/intro/1.png
    - assets/images/intro/2.png
    - assets/images/intro/3.png
    - assets/images/intro/4.png
    - assets/images/intro/5.png
    - assets/images/whatsapp.png
    - assets/images/about-jlf.jpeg
    - assets/images/faq.jpeg
    - assets/images/rekber-pembeli.jpeg
    - assets/images/rekber-penjual.jpeg
    - assets/images/bid.jpeg
    - assets/images/donation.jpeg
    - assets/images/new_update.png
    - assets/images/peoplecount.png
    - assets/images/animalcount.png
    - assets/images/calendar.png
    - assets/images/daftar_binatang_dilarang.jpg
    - assets/images/jlf-blue.png
    - assets/images/pets_login.jpg 
    - assets/images/pets_login.png                
    - assets/images/donation_banner.png
    - assets/images/sponsored_product.png
    - assets/images/promoted_seller.png
    - assets/images/hot_auction.png
    - assets/images/block-rekber.jpeg
    - assets/images/floatingbutton.png
    - assets/images/bannerdokterhewanhd.jpg
    - assets/images/ceritajlf.jpg
    - assets/images/sponsorseller.jpg
    - assets/images/map.png
    - assets/images/veterinarian.png
    - assets/images/coupon.png
    - assets/images/admin.png
    - assets/images/edit.png
    - assets/images/copy.png
    - assets/images/user.png
    - assets/images/share.png
    - assets/images/clap.png

  fonts:
  - family: RobotoMono
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
 